# Generated by Django 4.1.2 on 2022-10-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=1, unique=True)),
                ('description', models.TextField()),
                ('natureza', models.CharField(max_length=10)),
                ('sinal', models.CharField(max_length=1)),
            ],
        ),
    ]
